# Generated by Django 2.0.3 on 2018-03-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('login', models.TextField()),
                ('password', models.TextField()),
                ('birthday', models.DateField()),
                ('country', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
            ],
        ),
    ]
