# Generated by Django 2.0.3 on 2018-03-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180314_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='login',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
    ]
